### ISSUE TITLE
Long links break underlining

### ISSUE THREAD

**Issue by lf-** [niklasmtj/gatsby-starter-julia#10]
![2019-11-11T02:16:21-08:00](https://user-images.githubusercontent.com/6652840/68579593-58e82300-0429-11ea-8474-e8ac717ac26f.png)

^^^ It should be underlining the entire link over multiple lines but it only covers the last line

To reproduce: change the link in `post-1.md` to be something like:

```md
[Example.com very very very very very very very very very very very very very very very very long long long long link](example.com)
```

You can see the progress I'm making with this template (and steal my dark theme code if you wish) at [lf-/blog](https://github.com/lf-/blog). Thank you for developing it!

**Comment by niklasmtj** [comment]
Hi @lf-  again,
thank you for the issue! I have it on my list to fix for a long time now. Sad thing is that I forgot to fix it because I'm deep into university topics at the moment. 

I'm on it now let's see how to fix it. 
Firefox highlights the upper line and Chromium the bottom line. 

Thank you very much for your help!
