### ISSUE TITLE
Right-click on text triggers text selection

### ISSUE THREAD

**Issue by michaelbazos** [niklasmtj/gatsby-starter-julia#21]
In Chrome and Safari, right-clicking on a word triggers word selection. In some cases, like on the page with the list of blog articles, even a larger text portion gets selected.

**Comment by niklasmtj** [comment]
Hey,
Thank you for that issue. I will try to have a closer look into it in the next couple of days!
Niklas

**Comment by niklasmtj** [comment]
Hi,
I looked into it and changed the scope of the `<Link>` tag in `blog.js`. The large text selection on this page was because the `<Link>` tag was around the heading, date-section and excerpt section. I changed it to only wrap the heading. 
Text selection on right-click seems otherwise to be a normal behavior of Chrome and Safari. Another large selection on right-click for example is `H1H2H3H4H5H6ParagraphThis` in the excerpt of the last blog post. This is because Chrome seems to detect where spaces are and since there are none it will select the whole bit.

If you want to change it in your Gatsby blog check the commit above

Thanks again for this issue,
Niklas
