### ISSUE TITLE
Code viewer flashes when selecting in it

### ISSUE THREAD

**Issue by lf-** [niklasmtj/gatsby-starter-julia#8]
Demo: https://imgur.com/a/PKX9ikT

This was reproduced on the demo site linked on the top of the main repo page. I'm guessing some JavaScript is doing something to the selection for one frame and is causing this behaviour, but I don't know how to diagnose it.

**Comment by lf-** [comment]
Environment info: Chromium 78 on Arch Linux.

**Comment by niklasmtj** [comment]
Hi,
thank you for your issue. I tested it on MacOS in:
* Chrome 78
* Chromium 79.0
* Firefox Developer Edition 71.0
* Firefox 70.0.1
* Safari 12.1.2

This seems to only happen in Chromium based browsers. Firefox (both) and Safari did not show that flickering to me. Since I don't know how to diagnose it too I can only guess. 
The code is rendered in `<span>`s and I guess Chromium/Chrome handles them different than Firefox and Safari. 

I will have a look into `prism-react-renderer` in the next days since it seems to do the trick.

**Comment by niklasmtj** [comment]
@lf- I found what caused the flashing. Two paddings were the problem. Check the files in #9
It should work in Chromium/Chrome now as expected.
I will close this issue now. Thank you very much!
